# Generated by Django 2.2.1 on 2019-06-04 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name for the question set', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The name of the quiz.', max_length=30)),
                ('solutions', models.BooleanField(default=True, help_text='Tick this if you want solution feedback (eg You got the last question correct!)')),
                ('active', models.BooleanField(default=False, help_text='Tick this if the quiz is currently active')),
                ('questionSet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='mathsQuiz.QuestionSet')),
            ],
            options={
                'verbose_name_plural': 'quizzes',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='The title of the quesiton.', max_length=100)),
                ('questionText', models.TextField(help_text='The question text written out, including any multiple choice answers.')),
                ('solution', models.CharField(help_text='The correct solution for the question', max_length=100)),
                ('quizzes', models.ManyToManyField(related_name='questions', to='mathsQuiz.QuestionSet')),
            ],
        ),
        migrations.CreateModel(
            name='CompletionLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('score', models.IntegerField()),
                ('timeTaken', models.DurationField()),
                ('dateComplete', models.DateTimeField()),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mathsQuiz.Quiz')),
            ],
        ),
    ]
