# Generated by Django 2.2.1 on 2019-06-04 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathsQuiz', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='questionText',
            new_name='Question Text',
        ),
        migrations.RemoveField(
            model_name='question',
            name='quizzes',
        ),
        migrations.AddField(
            model_name='question',
            name='questionSet',
            field=models.ManyToManyField(related_name='questions', to='mathsQuiz.QuestionSet'),
        ),
    ]
