# Generated by Django 2.2.1 on 2019-05-31 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathsQuiz', '0002_auto_20190531_1532'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='quiz',
            new_name='questions',
        ),
    ]
