# Generated by Django 2.2.1 on 2019-06-10 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mathsQuiz', '0003_auto_20190604_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='active',
            new_name='visible',
        ),
    ]
