# Generated by Django 2.2.1 on 2019-06-01 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathsQuiz', '0003_auto_20190531_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='questions',
        ),
        migrations.AddField(
            model_name='question',
            name='quizzes',
            field=models.ManyToManyField(related_name='questions', to='mathsQuiz.Quiz'),
        ),
    ]
