# Generated by Django 2.2.1 on 2019-06-10 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathsQuiz', '0004_auto_20190610_1210'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='url',
            field=models.CharField(default='t', max_length=100),
            preserve_default=False,
        ),
    ]
