# Generated by Django 2.2.1 on 2019-06-11 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mathsQuiz', '0005_quiz_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='url',
        ),
        migrations.AddField(
            model_name='quiz',
            name='urlpath',
            field=models.CharField(default='', help_text='Add this url to the end of the root url to get the quiz', max_length=100),
        ),
    ]
